on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "<h3>Hey! Contributor, thank you talking out your valuable time to open an Issue</h3>"
          pr-message: "<h3>Hey! Contributor, thank you talking out your valuable time to open a Pull Request</h3>"
          footer: "Soon one of our maintaners will rewview it and provide you the feedback/suggestion. If you think it's something urgent, feel free to reach out <a href="https://twitter.com/home">Pradumna Saraf</a> on <b>Twitter</b>"
